/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_lee_signatureencryption_SingatureClass */

#ifndef _Included_com_lee_signatureencryption_SingatureClass
#define _Included_com_lee_signatureencryption_SingatureClass
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_lee_signatureencryption_SingatureClass
 * Method:    verificationPackage
 * Signature: (Ljava/lang/Object;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_lee_signatureencryption_SingatureClass_verificationPackage
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_lee_signatureencryption_SingatureClass
 * Method:    verificationSign
 * Signature: (Ljava/lang/Object;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_lee_signatureencryption_SingatureClass_verificationSign
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
